site_name: StateLayout
site_author: drake
site_description: StateLayout document
copyright: Copyright &copy; 2016 - 2020 Drake

repo_name: GitHub
repo_url: https://github.com/liangjingkanji/StateLayout

extra_css:
  - css/extra.css

docs_dir: 'docs'

theme:
  name: material
  custom_dir: docs/material

  palette:
    scheme: drake
    primary: white

  font: false

  language: zh

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true

nav:
  - 使用: 'index.md'
  - 生命周期: 'lifecycle.md'
  - 全局配置: 'global.md'
  - 传递数据: 'transfer.md'
  - 点击重试: 'retry.md'
  - 1.x文档: api/index.html
